apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: prometheus-operator-traefik-ingress
    k8s-app: traefik-ingress
    release: prometheus-operator
  name: prometheus-operator-traefik-ingress
  namespace: kube-system
subsets:
- addresses:
  - ip: 172.31.49.73
  - ip: 172.31.52.50
  - ip: 172.31.54.14
  - ip: 172.31.54.72
  - ip: 172.31.55.17
  - ip: 172.31.57.122
  - ip: 172.31.59.156
  - ip: 172.31.59.220
  ports:
  - name: admin
    port: 8080
    protocol: TCP