apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: prometheus-operator-cephfs
    k8s-app: kube-scheduler
    release: prometheus-operator
  name: prometheus-operator-cephfs
  namespace: kube-system
subsets:
- addresses:
  - ip: 172.17.3.32
  - ip: 172.17.3.33
  - ip: 172.17.3.34
  ports:
  - name: http-metrics
    port: 9283
    protocol: TCP